services:
  # Сервис для PostgreSQL
  db:
    image: postgres:latest
    container_name: finance_bot_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bot-network
    ports:
      - "5432:5432"
    restart: always
    mem_limit: 400m
    cpus: "0.5"

  # Сервис для вашего бота
  bot:
    image: finance_bot
    container_name: finance_bot
    depends_on:
      - db
    networks:
      - bot-network
    restart: always
    mem_limit: 100m
    cpus: "0.2"

networks:
  bot-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
