app:
  env: default
  name: expense-manager

tg:
  type_polling: long_polling
  debug: false


db:
  url: postgres://user:pass@postgres:5432/expenses?sslmode=disable
  max_conns: 10
  idle_conns: 5

redis:
  addr: localhost:6379
  db: 0
  pool_size: 5