services:
  test-server:
    image: test-server:latest
    build:
      context: ../../
      dockerfile: deployments/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://user:pass@postgres:5432/expenses?sslmode=disable
      REDIS_URL: redis://redis:6379
    networks:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d expenses"]
      interval: 5s
    networks:
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    networks:
      - redis

volumes:
  pgdata:
  redisdata:

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge