app:
  env: default
  name: expense-manager

db:
  url: postgres://user:pass@localhost:5432/expenses?sslmode=disable
  max_conns: 10
  idle_conns: 5

redis:
  addr: localhost:6379
  db: 0
  pool_size: 5