name: Expense Manager CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: "1.23"
  DB_NAME: expenses_test
  DB_USER: test_user
  DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
  DB_URL: postgres://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@localhost:5432/${{ env.DB_NAME }}?sslmode=disable
  REDIS_PORT: 6379
  REDIS_ADDR: localhost:${{ env.REDIS_PORT }}

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ env.DB_USER }} -d ${{ env.DB_NAME }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - ${{ env.REDIS_PORT }}:${{ env.REDIS_PORT }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: go test -v ./...
        env:
          DB_URL: ${{ env.DB_URL }}
          REDIS_ADDR: ${{ env.REDIS_ADDR }}